### ISSUE TITLE
Error building vault on ppc64le

### ISSUE THREAD

**Issue by vaibhavsood** [hashicorp/vault#2400]
Hi,

I am building vault as per steps here: https://github.com/hashicorp/vault#developing-vault

make fails for me with this error:

[root@pts00433-vm27 vault]# make
go generate
==> Removing old directory...
==> Building...
Number of parallel builds: 3

-->   linux/ppc64le: github.com/hashicorp/vault

1 errors occurred:
--> linux/ppc64le error: exit status 2
Stderr: # github.com/hashicorp/vault/vault
vault/mount.go:126: undefined: sort.Slice

make: *** [dev] Error 1

Any help why I could be getting this error?

Thanks!
Vaibhav

Env:

uname -a
>> Linux pts00433-vm27 3.10.0-327.18.2.el7.ppc64le #1 SMP Fri Apr 8 05:10:45 EDT 2016 ppc64le ppc64le ppc64le GNU/Linux

go version
>> go version go1.7.5 linux/ppc64le

go env
>> GOARCH="ppc64le"
GOBIN=""
GOEXE=""
GOHOSTARCH="ppc64le"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/go/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_ppc64le"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build300707509=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

**Comment by jefferai** [comment]
Nope. Try a `git pull`?

**Comment by AdallomRoy** [comment]
sort.Slice was only added in Go 1.8 (see here: https://github.com/golang/go/commit/22a2bdfedb95612984cec3141924953b88a607b7), therefor, terraform only compiles with Go 1.8+ (unlike the documented 1.7+)

**Comment by jefferai** [comment]
@AdallomRoy this is a Vault issue tracker, not a Terraform issue tracker.

**Comment by AdallomRoy** [comment]
Sorry, but it's the same issue anyway :) sort.Slice was introduced only in Go 1.8

**Comment by jefferai** [comment]
Right, but Vault documents that Go 1.8 is required. I don't know what Terraform documents as being required.

**Comment by AdallomRoy** [comment]
Yes, and again, sorry about that. Your documentation is correct and contains 1.8 as the minimum required while @vaibhavsood used 1.7.5

**Comment by jefferai** [comment]
Definitely sounds like the OP's problem. Thanks @AdallomRoy !
