### ISSUE TITLE
Kv2 inconsistent path segment list/show

### ISSUE THREAD

**Issue by ajfc84** [hashicorp/vault#20563]
When I input a path on kv2 web ui box like the following:

 ccloud/apikey/key1

I get redirected to the following url:

 https://my-vault.com/ui/vault/secrets/kv2/list/ccloud/apikey/key1
 
but if I input a shorter path based on the above like the following:

 ccloud/

I get redirected to the following url with a change from "list" to "show" on the segment before the secret name and a permissions error:

 https://my-vault.com/ui/vault/secrets/kv2/show/ccloud/

It is true that there is no permissions on a show segment, there is no permission "show", it should actually be a "list" segment.
Now if I manually change the url from "show" to "list" on the browser it works and there is no permissions error!

 https://my-vault.com/ui/vault/secrets/kv2/show/ccloud/ ->  https://my-vault.com/ui/vault/secrets/kv2/list/ccloud/

1. Authenticate in Vault Web UI
2. Select Secrets tab
3. Select KV2 secrets engine
4. Input an existing secret on the input box

The input box of kv2 should actually use a "list" path segment, not a "show" because that's the name of the permission to see the contents on the path, i.e., "list"!

Vault Server version: 1.12.1

Policy:

path "kv2/" {
    capabilities = [ "list" ]
}
path "kv2/data" {
    capabilities = [ "list" ]
}
path "kv2/data/ccloud/" {
    capabilities = [ "list" ]
}
path "kv2/data/ccloud/*" {
    capabilities = [ "list", "read" ]
}
path "kv2/metadata/ccloud/*" {
    capabilities = [ "list" ]
}
path "kv2/metadata/ccloud/*" {
    capabilities = [ "read" ]
}

**Comment by maxb** [comment]
I think the issue is just that the "secret name" input box currently only supports navigating directly to a secret - and not navigating to a listing of secrets contained in a subpath.

---

An aside about the policy you defined above - quite a bit of it is redundant and it can be simplified to this:

```
path "kv2/data/ccloud/*" {
  capabilities = ["read"]
}

path "kv2/metadata/ccloud/*" {
  capabilities = ["list", "read"]
}
```

* There is no point granting any access to `kv2/`, that path does not do anything other than return a warning instructing users it is incorrect to call that path (in a KV v2)
* There is no point granting `list` access to any path under `kv2/data`, as the `data` subcollection of a KV v2 does not implement `list` operations.
* There is no need to separate the grant of `list` and `read` to the `metadata` subcollection into multiple path blocks.

Consider also adding:
```
path "kv2/metadata/" {
  capabilities = ["list"]
}
```
unless you are unable to permit your users to see the list of what the top level of `kv2/` contains - with that, you'd be able to just click on `ccloud` rather than using the text entry box.

**Comment by Monkeychip** [comment]
@ajfc84 and @maxb thank you both for the comments. We are doing some internal work on KV for 1.15. I have added this ticket as one to review. It might be an inconsistency we can tackle alongside that work.
