### ISSUE TITLE
Compilation fails on fedora

### ISSUE THREAD

**Issue by waghanza** [hashicorp/vault#1218]
I am trying to compile the new source code on a `fedora` **23** docker image (**golang** `15`).

Here is my configuration

```dockerfile
FROM fedora:23
RUN dnf -y install git @development-tools @rpm-development-tools ruby-devel gcc-c++ golang
RUN gem update --no-ri --no-rdoc
RUN gem install fpm --no-ri --no-rdoc

RUN mkdir -p /root/go/src/github.com/
ENV GOPATH /root/go
ENV PATH "$$PATH:$$GOPATH/bin"
RUN git clone https://github.com/hashicorp/vault /root/go/src/github.com/hashicorp/vault
WORKDIR /root/go/src/github.com/hashicorp/vault
RUN git tag | sort -V | tail -n1 | xargs git checkout
RUN make bootstrap
```
I clone last tag (`0.5.1`) into $GOPATH/src/github.com/hashicorp/vault and switch to it.

* make bootstrap - was successful
* make - Fails

Here is the output,
```sh
[root@32f6452b1315 vault]# make
go generate 
VAULT_TOKEN= TF_ACC= go test $(go list ./... | grep -v /vendor/)  -timeout=120s -parallel=4
command/server.go:17:2: cannot find package "github.com/armon/go-metrics" in any of:
	/usr/lib/golang/src/github.com/armon/go-metrics (from $GOROOT)
	/root/go/src/github.com/armon/go-metrics (from $GOPATH)
vault/acl.go:4:2: cannot find package "github.com/armon/go-radix" in any of:
	/usr/lib/golang/src/github.com/armon/go-radix (from $GOROOT)
	/root/go/src/github.com/armon/go-radix (from $GOPATH)
builtin/logical/pki/path_config_urls.go:7:2: cannot find package "github.com/asaskevich/govalidator" in any of:
	/usr/lib/golang/src/github.com/asaskevich/govalidator (from $GOROOT)
	/root/go/src/github.com/asaskevich/govalidator (from $GOPATH)
builtin/logical/aws/client.go:6:2: cannot find package "github.com/aws/aws-sdk-go/aws" in any of:
	/usr/lib/golang/src/github.com/aws/aws-sdk-go/aws (from $GOROOT)
	/root/go/src/github.com/aws/aws-sdk-go/aws (from $GOPATH)
physical/dynamodb.go:16:2: cannot find package "github.com/aws/aws-sdk-go/aws/awserr" in any of:
	/usr/lib/golang/src/github.com/aws/aws-sdk-go/aws/awserr (from $GOROOT)
	/root/go/src/github.com/aws/aws-sdk-go/aws/awserr (from $GOPATH)
builtin/logical/aws/client.go:7:2: cannot find package "github.com/aws/aws-sdk-go/aws/credentials" in any of:
	/usr/lib/golang/src/github.com/aws/aws-sdk-go/aws/credentials (from $GOROOT)
	/root/go/src/github.com/aws/aws-sdk-go/aws/credentials (from $GOPATH)
physical/dynamodb.go:18:2: cannot find package "github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds" in any of:
	/usr/lib/golang/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds (from $GOROOT)
	/root/go/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds (from $GOPATH)
physical/dynamodb.go:19:2: cannot find package "github.com/aws/aws-sdk-go/aws/ec2metadata" in any of:
	/usr/lib/golang/src/github.com/aws/aws-sdk-go/aws/ec2metadata (from $GOROOT)
	/root/go/src/github.com/aws/aws-sdk-go/aws/ec2metadata (from $GOPATH)
builtin/logical/aws/client.go:8:2: cannot find package "github.com/aws/aws-sdk-go/aws/session" in any of:
	/usr/lib/golang/src/github.com/aws/aws-sdk-go/aws/session (from $GOROOT)
	/root/go/src/github.com/aws/aws-sdk-go/aws/session (from $GOPATH)
physical/dynamodb.go:21:2: cannot find package "github.com/aws/aws-sdk-go/service/dynamodb" in any of:
	/usr/lib/golang/src/github.com/aws/aws-sdk-go/service/dynamodb (from $GOROOT)
	/root/go/src/github.com/aws/aws-sdk-go/service/dynamodb (from $GOPATH)
physical/dynamodb.go:22:2: cannot find package "github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute" in any of:
	/usr/lib/golang/src/github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute (from $GOROOT)
	/root/go/src/github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute (from $GOPATH)
builtin/logical/aws/client.go:9:2: cannot find package "github.com/aws/aws-sdk-go/service/iam" in any of:
	/usr/lib/golang/src/github.com/aws/aws-sdk-go/service/iam (from $GOROOT)
	/root/go/src/github.com/aws/aws-sdk-go/service/iam (from $GOPATH)
physical/s3.go:19:2: cannot find package "github.com/aws/aws-sdk-go/service/s3" in any of:
	/usr/lib/golang/src/github.com/aws/aws-sdk-go/service/s3 (from $GOROOT)
	/root/go/src/github.com/aws/aws-sdk-go/service/s3 (from $GOPATH)
builtin/logical/aws/client.go:10:2: cannot find package "github.com/aws/aws-sdk-go/service/sts" in any of:
	/usr/lib/golang/src/github.com/aws/aws-sdk-go/service/sts (from $GOROOT)
	/root/go/src/github.com/aws/aws-sdk-go/service/sts (from $GOPATH)
physical/etcd.go:15:2: cannot find package "github.com/coreos/etcd/client" in any of:
	/usr/lib/golang/src/github.com/coreos/etcd/client (from $GOROOT)
	/root/go/src/github.com/coreos/etcd/client (from $GOPATH)
physical/etcd.go:16:2: cannot find package "github.com/coreos/etcd/pkg/transport" in any of:
	/usr/lib/golang/src/github.com/coreos/etcd/pkg/transport (from $GOROOT)
	/root/go/src/github.com/coreos/etcd/pkg/transport (from $GOPATH)
helper/mfa/duo/path_duo_access.go:7:2: cannot find package "github.com/duosecurity/duo_api_golang" in any of:
	/usr/lib/golang/src/github.com/duosecurity/duo_api_golang (from $GOROOT)
	/root/go/src/github.com/duosecurity/duo_api_golang (from $GOPATH)
helper/mfa/duo/duo.go:10:2: cannot find package "github.com/duosecurity/duo_api_golang/authapi" in any of:
	/usr/lib/golang/src/github.com/duosecurity/duo_api_golang/authapi (from $GOROOT)
	/root/go/src/github.com/duosecurity/duo_api_golang/authapi (from $GOPATH)
builtin/credential/cert/path_crls.go:9:2: cannot find package "github.com/fatih/structs" in any of:
	/usr/lib/golang/src/github.com/fatih/structs (from $GOROOT)
	/root/go/src/github.com/fatih/structs (from $GOPATH)
command/format.go:12:2: cannot find package "github.com/ghodss/yaml" in any of:
	/usr/lib/golang/src/github.com/ghodss/yaml (from $GOROOT)
	/root/go/src/github.com/ghodss/yaml (from $GOPATH)
builtin/credential/ldap/backend.go:6:2: cannot find package "github.com/go-ldap/ldap" in any of:
	/usr/lib/golang/src/github.com/go-ldap/ldap (from $GOROOT)
	/root/go/src/github.com/go-ldap/ldap (from $GOPATH)
builtin/logical/mysql/backend.go:9:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
	/usr/lib/golang/src/github.com/go-sql-driver/mysql (from $GOROOT)
	/root/go/src/github.com/go-sql-driver/mysql (from $GOPATH)
builtin/logical/cassandra/backend.go:8:2: cannot find package "github.com/gocql/gocql" in any of:
	/usr/lib/golang/src/github.com/gocql/gocql (from $GOROOT)
	/root/go/src/github.com/gocql/gocql (from $GOPATH)
builtin/credential/github/backend.go:4:2: cannot find package "github.com/google/go-github/github" in any of:
	/usr/lib/golang/src/github.com/google/go-github/github (from $GOROOT)
	/root/go/src/github.com/google/go-github/github (from $GOPATH)
builtin/logical/consul/client.go:6:2: cannot find package "github.com/hashicorp/consul/api" in any of:
	/usr/lib/golang/src/github.com/hashicorp/consul/api (from $GOROOT)
	/root/go/src/github.com/hashicorp/consul/api (from $GOPATH)
command/meta.go:17:2: cannot find package "github.com/hashicorp/errwrap" in any of:
	/usr/lib/golang/src/github.com/hashicorp/errwrap (from $GOROOT)
	/root/go/src/github.com/hashicorp/errwrap (from $GOPATH)
api/client.go:19:2: cannot find package "github.com/hashicorp/go-cleanhttp" in any of:
	/usr/lib/golang/src/github.com/hashicorp/go-cleanhttp (from $GOROOT)
	/root/go/src/github.com/hashicorp/go-cleanhttp (from $GOPATH)
logical/framework/backend.go:13:2: cannot find package "github.com/hashicorp/go-multierror" in any of:
	/usr/lib/golang/src/github.com/hashicorp/go-multierror (from $GOROOT)
	/root/go/src/github.com/hashicorp/go-multierror (from $GOPATH)
builtin/audit/syslog/backend.go:8:2: cannot find package "github.com/hashicorp/go-syslog" in any of:
	/usr/lib/golang/src/github.com/hashicorp/go-syslog (from $GOROOT)
	/root/go/src/github.com/hashicorp/go-syslog (from $GOPATH)
helper/salt/salt.go:11:2: cannot find package "github.com/hashicorp/go-uuid" in any of:
	/usr/lib/golang/src/github.com/hashicorp/go-uuid (from $GOROOT)
	/root/go/src/github.com/hashicorp/go-uuid (from $GOPATH)
vault/policy_store.go:9:2: cannot find package "github.com/hashicorp/golang-lru" in any of:
	/usr/lib/golang/src/github.com/hashicorp/golang-lru (from $GOROOT)
	/root/go/src/github.com/hashicorp/golang-lru (from $GOPATH)
api/ssh_agent.go:11:2: cannot find package "github.com/hashicorp/hcl" in any of:
	/usr/lib/golang/src/github.com/hashicorp/hcl (from $GOROOT)
	/root/go/src/github.com/hashicorp/hcl (from $GOPATH)
command/server/config.go:13:2: cannot find package "github.com/hashicorp/hcl/hcl" in any of:
	/usr/lib/golang/src/github.com/hashicorp/hcl/hcl (from $GOROOT)
	/root/go/src/github.com/hashicorp/hcl/hcl (from $GOPATH)
command/server.go:18:2: cannot find package "github.com/hashicorp/logutils" in any of:
	/usr/lib/golang/src/github.com/hashicorp/logutils (from $GOROOT)
	/root/go/src/github.com/hashicorp/logutils (from $GOPATH)
builtin/logical/mysql/path_role_create.go:9:2: cannot find package "github.com/lib/pq" in any of:
	/usr/lib/golang/src/github.com/lib/pq (from $GOROOT)
	/root/go/src/github.com/lib/pq (from $GOPATH)
command/token/testing.go:9:2: cannot find package "github.com/mitchellh/cli" in any of:
	/usr/lib/golang/src/github.com/mitchellh/cli (from $GOROOT)
	/root/go/src/github.com/mitchellh/cli (from $GOPATH)
logical/response.go:7:2: cannot find package "github.com/mitchellh/copystructure" in any of:
	/usr/lib/golang/src/github.com/mitchellh/copystructure (from $GOROOT)
	/root/go/src/github.com/mitchellh/copystructure (from $GOPATH)
command/token/helper_internal.go:9:2: cannot find package "github.com/mitchellh/go-homedir" in any of:
	/usr/lib/golang/src/github.com/mitchellh/go-homedir (from $GOROOT)
	/root/go/src/github.com/mitchellh/go-homedir (from $GOPATH)
logical/framework/field_data.go:9:2: cannot find package "github.com/mitchellh/mapstructure" in any of:
	/usr/lib/golang/src/github.com/mitchellh/mapstructure (from $GOROOT)
	/root/go/src/github.com/mitchellh/mapstructure (from $GOPATH)
audit/hashstructure.go:10:2: cannot find package "github.com/mitchellh/reflectwalk" in any of:
	/usr/lib/golang/src/github.com/mitchellh/reflectwalk (from $GOROOT)
	/root/go/src/github.com/mitchellh/reflectwalk (from $GOPATH)
command/audit_list.go:8:2: cannot find package "github.com/ryanuber/columnize" in any of:
	/usr/lib/golang/src/github.com/ryanuber/columnize (from $GOROOT)
	/root/go/src/github.com/ryanuber/columnize (from $GOPATH)
physical/zookeeper.go:12:2: cannot find package "github.com/samuel/go-zookeeper/zk" in any of:
	/usr/lib/golang/src/github.com/samuel/go-zookeeper/zk (from $GOROOT)
	/root/go/src/github.com/samuel/go-zookeeper/zk (from $GOPATH)
builtin/credential/userpass/path_login.go:9:2: cannot find package "golang.org/x/crypto/bcrypt" in any of:
	/usr/lib/golang/src/golang.org/x/crypto/bcrypt (from $GOROOT)
	/root/go/src/golang.org/x/crypto/bcrypt (from $GOPATH)
helper/pgpkeys/encrypt_decrypt.go:8:2: cannot find package "golang.org/x/crypto/openpgp" in any of:
	/usr/lib/golang/src/golang.org/x/crypto/openpgp (from $GOROOT)
	/root/go/src/golang.org/x/crypto/openpgp (from $GOPATH)
helper/pgpkeys/encrypt_decrypt.go:9:2: cannot find package "golang.org/x/crypto/openpgp/packet" in any of:
	/usr/lib/golang/src/golang.org/x/crypto/openpgp/packet (from $GOROOT)
	/root/go/src/golang.org/x/crypto/openpgp/packet (from $GOPATH)
builtin/logical/ssh/communicator.go:15:2: cannot find package "golang.org/x/crypto/ssh" in any of:
	/usr/lib/golang/src/golang.org/x/crypto/ssh (from $GOROOT)
	/root/go/src/golang.org/x/crypto/ssh (from $GOPATH)
builtin/logical/ssh/communicator.go:16:2: cannot find package "golang.org/x/crypto/ssh/agent" in any of:
	/usr/lib/golang/src/golang.org/x/crypto/ssh/agent (from $GOROOT)
	/root/go/src/golang.org/x/crypto/ssh/agent (from $GOPATH)
helper/password/password_unix.go:9:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
	/usr/lib/golang/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
	/root/go/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
physical/etcd.go:17:2: cannot find package "golang.org/x/net/context" in any of:
	/usr/lib/golang/src/golang.org/x/net/context (from $GOROOT)
	/root/go/src/golang.org/x/net/context (from $GOPATH)
builtin/credential/github/backend.go:8:2: cannot find package "golang.org/x/oauth2" in any of:
	/usr/lib/golang/src/golang.org/x/oauth2 (from $GOROOT)
	/root/go/src/golang.org/x/oauth2 (from $GOPATH)
Makefile:21: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by jefferai** [comment]
Hi @waghanza ,

As per the README, Go 1.6 is required, but you are trying to build with Go 1.5.

**Comment by jefferai** [comment]
Actually, I'm sorry -- that's a *post* 0.5.1 change, not a change for 0.5.1 itself.

In your situation, use `make dev`. Alternately, if you have `godep` installed, you can do a `godep restore`, then should be able to install normally.

**Comment by waghanza** [comment]
Hi,

Thanks for the tips anyway :+1: 

I run compilation now,
```dockerfile
FROM golang:1.6.0
RUN mkdir -p /root/go/src/github.com/
ENV GOPATH /root/go
ENV PATH "$$PATH:$$GOPATH/bin"
RUN git clone https://github.com/hashicorp/vault /root/go/src/github.com/hashicorp/vault
WORKDIR /root/go/src/github.com/hashicorp/vault
RUN git tag | sort -V | tail -n1 | xargs git checkout
RUN make bootstrap
```

**Comment by jefferai** [comment]
Cool. Two things to keep in mind. One is that 0.5.2 is *just* around the corner (should be today or tomorrow) and that *will* require Go 1.6 (it *may* work with GO15VENDOREXPERIMENT set but all of our testing is on 1.6). The other is that if you're working with the PKI backend, you should use 1.6 for sure, even for 0.5.1 (or, I can show you patches you'll want to apply to Go 1.5).

**Comment by waghanza** [comment]
sorry to re-open
but I have some fail test
```
# github.com/hashicorp/vault/vault
vault/expiration_test.go:159: not enough arguments in call to exp.RenewToken
vault/expiration_test.go:422: not enough arguments in call to exp.RenewToken
vault/expiration_test.go:453: not enough arguments in call to exp.RenewToken
vault/expiration_test.go:854: not enough arguments in call to exp.renewAuthEntry
# github.com/hashicorp/vault/api
api/ssh_agent_test.go:10: undefined: LoadSSHAgentConfig
make: *** [test] Error 2
```

**Comment by jefferai** [comment]
Behaves the same way for me too. Looks like tests were just broken at that commit.

**Comment by waghanza** [comment]
`0.5.1` seems to be corrupt
test passes :+1: on `master`
